
name: ddeploys asa ad

on: 
  push:
    branches: [ci/workflows]
    
jobs:
  Build-Production:
    runs-on: ubuntu-latest
    name: Build ubuntu - Node 16.18.x

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js 16.18.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.x
        cache: npm

    - name: Build App
      run: |
        npm install
        npm run build

    - name: Make App
      run: |
        mkdir habits-backend-build
        mkdir habits-backend-build/src
        mv dist/ src/
        mv src/ habits-backend-build/src/
        mv prisma/ habits-backend-build/prisma/
        mv package.json habits-backend-build/

    - name: Upload da pasta dist
      uses: actions/upload-artifact@v3
      with:
        name: habits-backend-build
        path: habits-backend-build/

  Deploy-Production:
    environment: production
    runs-on: ubuntu-latest
    name: Deploy AWS EC2
    needs: [Build-Production]

    steps:
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.x

    - name: Download do Build-Production
      uses: actions/download-artifact@v3
      with:
        name: habits-backend-build
        path: habits-backend-build/

    - name: Install Dependencies
      run: |
        echo "PORT=${{ vars.AWS_API_PORT }}" > habits-backend-build/.env
        cd habits-backend-build 
        npm install

    - name: Login AWS EC2 Ubuntu
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_API_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "habits-backend-build/"
        REMOTE_HOST: ${{ secrets.AWS_API_HOST }}
        REMOTE_USER: ${{ secrets.AWS_API_USER }}
        TARGET: "${{ vars.AWS_API_TARGET }}"
        EXCLUDE: "/habits-backend-build/"

