
name: ddeploys asa ad

on: 
  push:
    branches: [ci/workflows]
    
jobs:
  Deploy-Production:
    environment: production
    runs-on: ubuntu-latest
    name: Deploy AWS EC2

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.x

    - name: Create file key AWS
      run: |
        echo "${{ secrets.AWS_API_PRIVATE_KEY }}" > habitskey.pem
        chmod 400 habitskey.pem

    - name: Login AWS EC2 Ubuntu
      run: |
        ssh -v

    - name: Upload Permission
      uses: actions/upload-artifact@v3
      with:
        name: habitskey
        path: habitskey.pem
