
name: ddeploys asa ad

on: 
  push:
    branches: [ci/workflows]
    
jobs:
  Deploy-Production:
    environment: production
    runs-on: ubuntu-latest
    name: Deploy AWS EC2

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.x

    - run: npm install
    - run: npm run build

    - name: Login AWS EC2 Ubuntu
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_API_PRIVATE_KEY  }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.AWS_API_HOST }}
        REMOTE_USER: ${{ secrets.AWS_API_USER }}
        TARGET: ${{ vars.AWS_API_TARGET }}
        EXCLUDE: "/dist/, /node_modules/"

