
name: ddeploys asa ad

on: 
  push:
    branches: [ci/workflows]
    
jobs:
  Deploy-Production:
    environment: production
    runs-on: ubuntu-latest
    name: Deploy AWS EC2

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.18.x

    - run: echo ${{ vars.AWS_API_PRIVATE_KEY }} >> habistkey.pem
    
    - name: Upload Permission
      uses: actions/upload-artifact@v3
      with:
        path: habistkey.pem
