name: Release CI/CD

on:
  push:
    branches: [development]

jobs:
  Sast-Release:
    runs-on: ubuntu-latest
    name: SAST Scan

    permissions:
      security-events: write

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
      with:
        args: '. --sarif --output results.sarif || true'

    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  Build-Release:
    runs-on: ubuntu-latest
    name: Build ubuntu
    needs: [Sast-Release]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js 16.18.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.x
        cache: npm

    - name: Build App
      run: |
        npm install
        npm run build
        mkdir habits-backend-build
        mkdir habits-backend-build/src
        mv dist/ habits-backend-build/src/
        mv prisma/ habits-backend-build/prisma/
        mv package.json habits-backend-build/
        ls -la habits-backend-build/

    - name: Upload da pasta Build
      uses: actions/upload-artifact@v3
      with:
        name: habits-backend-build
        path: habits-backend-build/