name: SAST - NodeJS Scan

on:
  push:
    branches: [master, development]
    
jobs:
  Sast:
    runs-on: ubuntu-latest
    name: NodeJS Scan

    permissions:
      security-events: write

    steps:
    - name: Checkout GitHub code
      uses: actions/checkout@v3

    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
      with:
        args: '. --sarif --output results.sarif || true'

    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif